### ISSUE TITLE
Linux File Not Found error when using extract

### ISSUE THREAD

**Issue by MorgenAnSpyrys** [mappingtools/Mapperator#8]
Tried to run Mapperator on linux and this is the output I got, this seems to stem from some kind of FS issue (and also the fact I cannot specify an osu folder)

```bash
[desktop-fedora@p200300e2b71186290fc596e6dc45fbe3 Downloads]$ ./Mapperator.ConsoleAppLinux extract -s Ranked -m Standard -a Starrodkirby86 -o KirbyData
Unhandled exception. System.IO.FileNotFoundException: Unable to find the specified file.
   at OsuParsers.Decoders.DatabaseDecoder.DecodeOsu(String path)
   at Mapperator.ConsoleApp.DbManager.GetAll()
   at Mapperator.ConsoleApp.Program.DoDataExtraction(ExtractOptions opts)
   at Mapperator.ConsoleApp.Program.<>c.<Main>b__5_1(ExtractOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Mapperator.ConsoleApp.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by OliBomby** [comment]
You can specify an osu folder. There should be a `config.json` next to the executable with some paths. This is the contents:
```
{
  "OsuPath": "C:\\Users\\name\\AppData\\Local\\osu!",
  "SongsPath": "C:\\Users\\name\\AppData\\Local\\osu!\\Songs"
}
```

**Comment by MorgenAnSpyrys** [comment]
That worked, should probably be pointed out in the README though, thanks for your help :)

**Comment by OliBomby** [comment]
I added it to the README
